### ISSUE TITLE
Friend Codes one digit short in "Friend Codes" Tab

### ISSUE THREAD

**Issue by limewirez** [DismissedGuy/wiimmfi-rpc#21]
Friend Codes for the Wii seem to be one digit short, I can't enter the last digit (only 618 instead of 6183). Maybe I'm doing something wrong?

**Comment by malmeloo** [comment]
Hi!

The friend code field is capped at 15 characters because game-specific codes consist of 3 pairs of 4 characters separated by dashes (XXXX-XXXX-XXXX).
Obviously I can't read your mind, but the issue you are facing is what happens when you try to enter a Wii-specific friend code (XXXX-XXXX-XXXX-XXXX) without dashes, at which point it caps out one character before the end.

You are supposed to enter the friend codes for each specific game you want to use this program with. Depending on the game you can find it in the settings menu, at the profiles screen (as is the case for mario kart wii) or when you join online mode.

Hopefully that helps, if you have further questions just let me know.

**Comment by malmeloo** [comment]
I'm going to close this issue now, let me know if it's still unclear.
